import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import localFont from "next/font/local";
import Footer from "@/components/Footer";

const figTree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 1. Setup the Heading Font (e.g., for H1, H2, Hero sections)
const headingFont = localFont({
  src: "./fonts/Redaction-Regular.woff2", // Make sure this matches your filename
  variable: "--font-heading", // CSS Variable for Tailwind
  display: "swap",
  // Force bold if it's a single weight file
});

const headingFontItalic = localFont({
  src: "./fonts/Redaction-Italic.woff2", // Make sure this matches your filename
  variable: "--font-heading-italic", // CSS Variable for Tailwind
  display: "swap",
  weight: "700", // Force bold if it's a single weight file
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figTree.variable} ${geistMono.variable} ${headingFont.variable} ${headingFontItalic.variable}  antialiased`}
      >
        <Navbar />
        {children}
        <section className=" relative w-screen min-h-[calc(100vh*3/4)] bg-black text-white flex items-center justify-center ">
          <Footer />
        </section>
      </body>
    </html>
  );
}
